/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package paquete;

/**
 *
 * @author Alumno
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_title = new javax.swing.JLabel();
        lbl_movie = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Categorias = new javax.swing.JMenu();
        Terror = new javax.swing.JMenu();
        terror_1 = new javax.swing.JMenuItem();
        terror_2 = new javax.swing.JMenuItem();
        No = new javax.swing.JMenu();
        No_1 = new javax.swing.JMenuItem();
        No_2 = new javax.swing.JMenuItem();
        Sci = new javax.swing.JMenu();
        sci_1 = new javax.swing.JMenuItem();
        sci_2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_title.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lbl_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_title.setText("Peliculas");
        lbl_title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbl_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 300, 400));
        jPanel1.add(lbl_movie, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 300, 400));

        Categorias.setText("Categoria");

        Terror.setText("Terror");

        terror_1.setText("FIVE NIGHTS AT FREDDYS");
        terror_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terror_1ActionPerformed(evt);
            }
        });
        Terror.add(terror_1);

        terror_2.setText("NO BIGES");
        terror_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terror_2ActionPerformed(evt);
            }
        });
        Terror.add(terror_2);

        Categorias.add(Terror);

        No.setText("no");

        No_1.setText("NO HELP");
        No_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                No_1ActionPerformed(evt);
            }
        });
        No.add(No_1);

        No_2.setText("NO SEQUEL");
        No_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                No_2ActionPerformed(evt);
            }
        });
        No.add(No_2);

        Categorias.add(No);

        Sci.setText("Sci-fi");

        sci_1.setText("STAR WARS");
        sci_1.setToolTipText("");
        sci_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sci_1ActionPerformed(evt);
            }
        });
        Sci.add(sci_1);

        sci_2.setText("STAR WARS 2");
        sci_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sci_2ActionPerformed(evt);
            }
        });
        Sci.add(sci_2);

        Categorias.add(Sci);
        Categorias.add(jSeparator1);

        jMenuItem3.setText("Salir");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        Categorias.add(jMenuItem3);

        jMenuBar1.add(Categorias);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void terror_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terror_1ActionPerformed
        lbl_movie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/terror_1.jpg"))); 
        lbl_title.setText("Terror");
    }//GEN-LAST:event_terror_1ActionPerformed

    private void terror_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terror_2ActionPerformed
        lbl_movie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/terror_2.jpg"))); 
        lbl_title.setText("Terror");
    }//GEN-LAST:event_terror_2ActionPerformed

    private void No_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_No_1ActionPerformed
        lbl_movie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/no_1.jpg"))); 
        lbl_title.setText("NO");
    }//GEN-LAST:event_No_1ActionPerformed

    private void No_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_No_2ActionPerformed
        lbl_movie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/no_2.jpg"))); 
        lbl_title.setText("NO");
    }//GEN-LAST:event_No_2ActionPerformed

    private void sci_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sci_1ActionPerformed
        lbl_movie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sci_1.jpg"))); 
        lbl_title.setText("SCI-FI");        
    }//GEN-LAST:event_sci_1ActionPerformed

    private void sci_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sci_2ActionPerformed
        lbl_movie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sci_2.jpg"))); 
        lbl_title.setText("SCI-FI");      
    }//GEN-LAST:event_sci_2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Categorias;
    private javax.swing.JMenu No;
    private javax.swing.JMenuItem No_1;
    private javax.swing.JMenuItem No_2;
    private javax.swing.JMenu Sci;
    private javax.swing.JMenu Terror;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lbl_movie;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JMenuItem sci_1;
    private javax.swing.JMenuItem sci_2;
    private javax.swing.JMenuItem terror_1;
    private javax.swing.JMenuItem terror_2;
    // End of variables declaration//GEN-END:variables
}
